### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by AbnirHencazs** [Job79/EasyTcp#36] opened 2020-07-03 18:02 UTC
Hi,

I tried downloading this package from NuGet package Manager in Visual Studio 2019 and i get this error:

"No se pudo instalar el paquete 'EasyTcp 3.5.0'. Está intentando instalar este paquete en un proyecto que tiene '.NETFramework,Version=v4.7.2' como destino, pero el paquete no contiene referencias de ensamblado o archivos de contenidocompatibles con dicho marco. Para obtener más información, póngase en contacto con el autor del paquete."		

From what i understand i should change my NetFramework Version in the project i'm using. Is this correct?

**Comment by AbnirHencazs** [comment] 2020-07-03 18:08
so i tried targeting different NETFramework versions but none seems to work.

**Comment by Job79** [comment] 2020-07-03 19:07
Hello, thanks for creating an issue.

Seems like the problem is that this package is published with .net standard 2.1.
.net standard 2.1 does not work with .net framework. (only with .net core) 
I will look into downgrading to .net framework 2.0 tomorrow

**Comment by AbnirHencazs** [comment] 2020-07-03 19:33
Much appreciated.

**Comment by Job79** [comment] 2020-07-04 14:31
Hello @AbnirHencazs,
I added support for .net standard 2.0 to EasyTcp (3.6.0)
Could you check again?
I'll close this issue once you confirm.

**Comment by AbnirHencazs** [comment] 2020-07-06 14:20
Hi,

I succesfully installed the package targeting .NET Framewaork 4.7.2

For this i thank you.

**Comment by Job79** [comment] 2020-07-06 14:22
Thanks for confirming and bringing this issue to my attention!

**Closed by Job79** 2020-07-06 14:22 UTC
Labels: enhancement
