### ISSUE TITLE
SSL Certificates 

### ISSUE THREAD

**Issue by bnaambo** [Job79/EasyTcp#55] opened 2020-10-15 16:08 UTC
hey sorry for opening new issue.
How can i make a Valid Server SSL Certificate i tried it with XCA software but it says its invalid

**Comment by bnaambo** [comment] 2020-10-15 16:36
actually i got it to work by creating a CA and creating  new certificate signed by my CA and import the CA into my Systems Trusted CA. when i Connect 1st time to my server with the CA it works but on 2nd connect or 2nd client the server crashes and give the folowing exception: The server mode SSL must use a certificate with the associated private key.'

**Comment by bnaambo** [comment] 2020-10-15 16:37
the Certificate used is exported as Ceritficated togehter with privatekey

**Comment by Job79** [comment] 2020-10-15 17:09
Hello @bnaambo,

I generated the certificate found in the example project and unit tests like this with openssl(linux):
```sh
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost'
openssl pkcs12 -export -out certificate.pfx -inkey key.pem -in cert.pem
```
First line generates a certificate and key, second line combines them into a .pem file (used by the c# X509Certificate2)
Is your certificate a valid .pem file? As far as I know are these the only valid options for the X509Certificate2 constructor. (when the certificate is used by a server)

This certificate isn't signed which makes it invalid and for testing purposes only (because man in the middle attacks are possible for non-signed certificates)
I do not have any experience with signing certificates because it is mostly paid.

Use the boolean option in the .UseSsl function when using an invalid certificate for testing purposes.

**Comment by bnaambo** [comment] 2020-10-15 17:17
hey yes its pfx signed by my own CA which is in trusted CA in MMC. it works for first connect but when i connect with 2nd client it crashed the server wit htat error The server mode SSL must use a certificate with the associated private key.'

**Comment by Job79** [comment] 2020-10-15 17:21
> hey yes its pfx signed by my own CA which is in trusted CA in MMC. it works for first connect but when i connect with 2nd client it crashed the server wit htat error The server mode SSL must use a certificate with the associated private key.'

Sounds like a problem with the library, can you share some code to reproduce?

**Comment by bnaambo** [comment] 2020-10-15 17:29
Server Side
`
EasyTcpActionServer server = new EasyTcpActionServer();
        internal bool IsRunning = false;
        internal void Start(ushort port)
        {
         
            server.UseSsl(new X509Certificate2("hmsdev.pfx", "12qwaszxS")).Start(port);
            IsRunning = server.IsRunning;
            server.OnConnect += Server_OnConnect;
            server.OnDisconnect += Server_OnDisconnect;
        }

        private void Server_OnDisconnect(object sender, EasyTcpClient e)
        {
            Console.WriteLine($"Client Disconnected! {e.BaseSocket.RemoteEndPoint}");
        }

        private void Server_OnConnect(object sender, EasyTcpClient e)
        {
            Console.WriteLine($"Client Connected! {e.BaseSocket.RemoteEndPoint}");
        }
`
Client Side
` 
EasyTcpClient client = new EasyTcpClient();
        public Loginfrm()
        {

            InitializeComponent();
            if (!client.UseSsl("localhost").Connect("127.0.0.1", 25123))
            {
                lblStatus.Text = "Offline";
                lblStatus.ForeColor = Color.Red;
                btnLogin.Enabled = false;
                tbxEmployeeid.Enabled = false;
                tbxPassword.Enabled = false;

            }
            else
            {
                lblStatus.Text = "Online";
                lblStatus.ForeColor = Color.Green;
                btnLogin.Enabled = true;
                tbxEmployeeid.Enabled = true;
                tbxPassword.Enabled = true;
               
            }
        }`

**Comment by Job79** [comment] 2020-10-15 18:26
Thanks!

I think I found the problem, the certificate gets disposed when the first client disconnects. Then throws an error when the second client connects.
Will try to publish a fix when I have some time.
You could try to clone the project, go to EasyTcp.Encryption/Protocols/Tcp/Ssl/DefaultSslProtocol and remove line 153.

**Comment by bnaambo** [comment] 2020-10-15 18:27
ok let me try that i give u feedback asap

**Comment by bnaambo** [comment] 2020-10-15 19:19
i removed line 153 from EasyTcp.Encryption/Protocols/Tcp/Ssl/DefaultSslProtocol now its working. Thanks Man

**Comment by Job79** [comment] 2020-10-16 14:17
> i removed line 153 from EasyTcp.Encryption/Protocols/Tcp/Ssl/DefaultSslProtocol now its working. Thanks Man

Thanks for testing! I published a new version of EasyTcp.Encryption to nuget.  (2.3.4, commit: ba9dbf9db171db77235aa1ee935b96d333b53d5a)
Will close this issue now because it should be resolved, please reopen when any other issues occur.

**Closed by Job79** 2020-10-16 14:17 UTC
Labels: bug
